import Head from 'next/head'
import requestIp from 'request-ip'

export default function Home({ip}) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        {ip}
      </div>
    </>
  )
}


export async function getServerSideProps({req, res}){
  
  const ip = requestIp.getClientIp(req)
  
  return {
    props:{
      ip
    }
  }
}